// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/drawiin/go-orders-service/internal/entity"
	"github.com/drawiin/go-orders-service/internal/event"
	"github.com/drawiin/go-orders-service/internal/infra/db"
	"github.com/drawiin/go-orders-service/internal/infra/repository"
	"github.com/drawiin/go-orders-service/internal/infra/web"
	"github.com/drawiin/go-orders-service/internal/usecase"
	"github.com/drawiin/go-orders-service/pkg/events"
	"github.com/google/wire"
)

import (
	_ "github.com/go-sql-driver/mysql"
)

// Injectors from wire.go:

func NewCreateOrderUseCase(db2 *db.Queries, eventDispatcher events.EventDispatcherInterface) *usecase.CreateOrderUseCase {
	orderRepository := repository.NewOrderRepository(db2)
	orderCreated := event.NewOrderCreated()
	createOrderUseCase := usecase.NewCreateOrderUseCase(orderRepository, orderCreated, eventDispatcher)
	return createOrderUseCase
}

func NewGetAllOrdersUseCase(db2 *db.Queries) *usecase.GetAllOrdersUseCase {
	orderRepository := repository.NewOrderRepository(db2)
	getAllOrdersUseCase := usecase.NewGetAllOrdersUseCase(orderRepository)
	return getAllOrdersUseCase
}

func NewGetOrderByIdUseCase(db2 *db.Queries) *usecase.GetOrderByIdUseCase {
	orderRepository := repository.NewOrderRepository(db2)
	getOrderByIdUseCase := usecase.NewGetOrderByIdUseCase(orderRepository)
	return getOrderByIdUseCase
}

func NewWebOrderHandler(db2 *db.Queries, eventDispatcher events.EventDispatcherInterface) *web.WebOrderHandler {
	orderRepository := repository.NewOrderRepository(db2)
	orderCreated := event.NewOrderCreated()
	webOrderHandler := web.NewWebOrderHandler(eventDispatcher, orderRepository, orderCreated)
	return webOrderHandler
}

// wire.go:

var setOrderRepositoryDependency = wire.NewSet(repository.NewOrderRepository, wire.Bind(new(entity.OrderRepositoryInterface), new(*repository.OrderRepository)))

var setEventsDispatcherDependency = wire.NewSet(events.NewEventDispatcher, event.NewOrderCreated, wire.Bind(new(events.EventInterface), new(*event.OrderCreated)), wire.Bind(new(events.EventDispatcherInterface), new(*events.EventDispatcher)))

var setOrderCreatedEvent = wire.NewSet(event.NewOrderCreated, wire.Bind(new(events.EventInterface), new(*event.OrderCreated)))
